Universe = vanilla
Executable = /data/user/hhamdaoui/nuclearite_analysis/genscripts/wrap_L1_L2_proc.sh
Arguments  = -i $Fp(file)/$Fnx(file) -b /data/user/hhamdaoui/MC_nuclearites/MC2_L1_poleprocessed/$Fnx(file) -o /data/user/hhamdaoui/MC_nuclearites/MC3_L2_northprocessed/$Fnx(file)

initialdir = /data/user/hhamdaoui/MC_nuclearites/

Log    = /scratch/hhamdaoui/nuclearite/log_MC2_MC3_L1_L2_proc/$(Year)-$(Month)-$(Day).$Fn(file).$(cluster).$(Process).log
Output = /scratch/hhamdaoui/nuclearite/log_MC2_MC3_L1_L2_proc/$(Year)-$(Month)-$(Day).$Fn(file).$(cluster).$(Process).out
Error  = /scratch/hhamdaoui/nuclearite/log_MC2_MC3_L1_L2_proc/$(Year)-$(Month)-$(Day).$Fn(file).$(cluster).$(Process).err

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
notification            = NEVER

request_memory   = 4GB
request_disk     = 2GB

Queue file from /data/user/hhamdaoui/MC_nuclearites/filenames_MC1.txt